version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cv7ld40cj0f6"
s3_prefix = "myStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
